### ISSUE TITLE
Server side history is useful and needs testing.

### ISSUE THREAD

**Issue by terjekv** [unioslo/mreg-cli#194]
Commands such as `host history` are actually used and actually useful. They need to be supported going forward, and this means we should have tests to cover this use case.

```[tasklist]
### Tasks
- [x] Create a specific block in the testsuite and its results that deal with `host history`.
- [x] Check what other history functionality we actually support.
- [x] Test all supported history lookups.
```

**Comment by terjekv** [comment]
Fixed in https://github.com/unioslo/mreg-cli/pull/199
